version: '3.4'

services:
  cliverapi:
    image: ${DOCKER_REGISTRY-}cliverapi
    environment:
      ConnectionStrings__DbContext: "Server=CliverProd.mssql.somee.com;Initial Catalog=CliverProd;User=ddatdt05_SQLLogin_1;Password=gqrchhqkso;"
    build:
      context: .
      dockerfile: CliverApi/Dockerfile
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - 1450:1433 
    environment:
      MSSQL_PID: "Express"
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
