name: Build and deploy ASP.Net Core app to an Azure Web App

env:
  AZURE_WEBAPP_NAME: cliverAPI    # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'                 # set this to the .NET Core version to use
  DOTNET_ROOT: C:\Program Files\dotnet

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Create a new working directory
        run: |
          mkdir build
          cp -R ./* build/
          cd build

      - name: Clear cache
        run: |
          rm -rf ./.github
          rm -rf ./node_modules

      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          include-prerelease: true

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v2
        with:
          path: ~/AppData/Local/NuGet/Cache
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build with dotnet
        run: dotnet build "CliverApi/CliverAPI.csproj" --configuration Release

      - name: dotnet publish
        run: dotnet publish "CliverApi/CliverAPI.csproj" -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
